input_data:
    data_location: mock
    data_format: csv

project:
    project_name: mock_project
    description: mock_description
    version: mock_version

features:
    - 'mock'

output_data:
    output_location: mock
